# Generated by Django 4.2.3 on 2023-08-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(max_length=20)),
                ('Mentor', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='files/covers')),
            ],
        ),
    ]
