# Generated by Django 4.2.3 on 2023-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LADC', models.PositiveIntegerField(max_length=20)),
                ('AP', models.PositiveIntegerField(max_length=20)),
                ('ENG', models.PositiveIntegerField(max_length=20)),
                ('DM', models.PositiveIntegerField(max_length=20)),
                ('VEGC', models.PositiveIntegerField(max_length=20)),
                ('Java', models.PositiveIntegerField(max_length=20)),
                ('DLD', models.PositiveIntegerField(max_length=20)),
                ('BEE', models.PositiveIntegerField(max_length=20)),
                ('DBMS', models.PositiveIntegerField(max_length=20)),
                ('PS', models.PositiveIntegerField(max_length=20)),
                ('CHEM', models.PositiveIntegerField(max_length=20)),
                ('SLL', models.PositiveIntegerField(max_length=20)),
                ('DBMSL', models.PositiveIntegerField(max_length=20)),
                ('JPL', models.PositiveIntegerField(max_length=20)),
                ('LSPD', models.PositiveIntegerField(max_length=20)),
                ('DEVC', models.PositiveIntegerField(max_length=20)),
                ('EWS', models.PositiveIntegerField(max_length=20)),
                ('DS', models.PositiveIntegerField(max_length=20)),
                ('DSL', models.PositiveIntegerField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Rollno',
            field=models.CharField(max_length=20),
        ),
    ]
