# Generated by Django 4.2.3 on 2023-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_progress_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='AP',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='BEE',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='CHEM',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DBMS',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DBMSL',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DEVC',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DLD',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DM',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DS',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='DSL',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='ENG',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='EWS',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='JPL',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='Java',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='LADC',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='LSPD',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='PS',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='SLL',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='VEGC',
            field=models.PositiveIntegerField(),
        ),
    ]
