# Generated by Django 4.2.3 on 2023-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_progress_ap_alter_progress_bee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.PositiveIntegerField()),
                ('LADC', models.PositiveIntegerField()),
                ('AP', models.PositiveIntegerField()),
                ('ENG', models.PositiveIntegerField()),
                ('DM', models.PositiveIntegerField()),
                ('VEGC', models.PositiveIntegerField()),
                ('Java', models.PositiveIntegerField()),
                ('DLD', models.PositiveIntegerField()),
                ('BEE', models.PositiveIntegerField()),
                ('DBMS', models.PositiveIntegerField()),
                ('PS', models.PositiveIntegerField()),
                ('CHEM', models.PositiveIntegerField()),
                ('SLL', models.PositiveIntegerField()),
                ('DBMSL', models.PositiveIntegerField()),
                ('JPL', models.PositiveIntegerField()),
                ('LSPD', models.PositiveIntegerField()),
                ('DEVC', models.PositiveIntegerField()),
                ('EWS', models.PositiveIntegerField()),
                ('DS', models.PositiveIntegerField()),
                ('DSL', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
